# Generated by Django 3.2.4 on 2021-08-01 09:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_fullpage_narrowpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(default='')), ('logo_item', wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.core.blocks.RichTextBlock())]))]),
        ),
    ]
